name: Deployment pipeline

on:
  push:
    branches:
      - main
jobs:
 avoid_reduncy:
    runs-on: ubuntu-20.04
    steps: 
      - name: Cancel previous redundant builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
    env:
      COMMIT_MESSAGES: ${{ join(github.event.commits.*.message) }}
 
 lint:
    runs-on: ubuntu-20.04
    env: 
     MONGOURI: ${{secrets.MONGO.URI}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: npm install 
        run: npm ci
      - name: lint fix
        run: npm run lint:fix
      - name: lint
        run: npm run eslint

 build:
    runs-on: ubuntu-20.04
    needs: lint
    steps:
       - uses: actions/checkout@v3
         with: 
           fetch-depth: 0
       - uses: actions/setup-node@v2
         with:
           cache: 'npm'
           node-version: '16'
       - name: npm install FRONT
         working-directory: ./FRONT
         run: npm ci
       - name: build FRONT
         working-directory: ./FRONT
         run: npm run build 
       - uses: actions/upload-artifact@v2         
         with: 
           name: build
           path: ./FRONT/build
 tests:
     runs-on: ubuntu-20.04
     needs: [build,lint]
     steps:
      - uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: '16'
      - name: npm install 
        run: npm ci
      - uses: actions/download-artifact@v2         
        with: 
           name: build
           path: ./FRONT/build
      - uses: cypress-io/github-action@v2
        env: 
          MONGO_URI: ${{secrets.MONGO_URI}}
          run : echo $MONGO_URI
        with:  
         browser: chrome
         headless: true
         command: npx cypress run
         start: npm run start
         wait-on: 'http://localhost:3001'
     
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos
    
      

 deploy:
      if: ${{ github.event_name == 'push' && !contains(env.COMMIT_MESSAGES, '#skip') }}
      runs-on: ubuntu-20.04
      needs: [ lint,build,tests]         
      steps:
        - uses: actions/checkout@v3
          with: 
           fetch-depth: 0
        - uses: actions/download-artifact@v2         
          with: 
           name: build
           path: ./FRONT/build
        - uses: akhileshns/heroku-deploy@v3.12.12 
          with:
            heroku_api_key: ${{secrets.HEROKU_TOKEN}}
            heroku_app_name: "persons00"
            heroku_email: ${{secrets.HEROKU_EMAIL}}
            healthcheck: "https://persons00.herokuapp.com"
            
            delay: 1
            rollbackonhealthcheckfailed: true
          
 versioning:
     runs-on: ubuntu-20.04  
     needs: deploy
     steps:
     - uses: actions/checkout@v2
       with:
        fetch-depth: '0'
     - uses: anothrNick/github-tag-action@1.36.0
       env:
           GITHUB_TOKEN: ${{ github.token }}
           WITH_V: true
           DEFAULT_BUMP: patch

           
