name: Deployment pipeline

on:
  push:
    branches:
      - main
jobs:
 avoid_reduncy:
    runs-on: ubuntu-20.04
    steps: 
      - name: Cancel previous redundant builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
 
 lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: npm install 
        run: npm ci
      - name: lint fix
        run: npm run lint:fix
      - name: lint
        run: npm run eslint

 build:
    runs-on: ubuntu-20.04
    needs: lint
    steps:
       - uses: actions/checkout@v3
         with: 
           fetch-depth: 0
       - uses: actions/setup-node@v2
         with:
           cache: 'npm'
           node-version: '16'
       - name: npm install FRONT
         working-directory: ../FRONT
         run: npm ci
       - name: build FRONT
         working-directory: ../FRONT
         run: npm run build 
       - uses: actions/upload-artifact@v2
         with: 
           name: dist
           path: dist
